[pytest]
addopts = -ra
base_url = https://www.saucedemo.com
markers =
    ui: UI tests
    api: API tests
    selenium: Selenium UI tests
    playwright: Playwright tests
    flaky: Flaky tests (retry allowed)
